export const mockApplications = [
  {
    id: 1,
    name: "Ahmad Rizki",
    email: "ahmad.rizki@email.com",
    appliedDate: "16/1/2024",
    location: "Jakarta",
    status: "Under Review",
    notes: "Kandidat potensial dengan pengalaman yang relevan",
  },
  {
    id: 2,
    name: "Sari Dewi",
    email: "sari.dewi@email.com",
    appliedDate: "12/1/2024",
    location: "Surabaya",
    status: "Interview",
    notes: "Lulus tahap screening, dijadwalkan interview",
  },
  {
    id: 3,
    name: "Budi",
    email: "budi.santoso@email.com",
    appliedDate: "18/1/2024",
    location: "Jakarta",
    status: "Pending",
    notes: "Baru melamar, menunggu review",
  },
  {
    id: 4,
    name: "Santoso",
    email: "budi@example.com",
    status: "Pending",
    appliedDate: "2025-09-01",
    location: "Jakarta",
    skills: ["React", "Node.js"],
  },
  {
    id: 5,
    name: "Aminah",
    email: "siti@example.com",
    status: "Interview",
    appliedDate: "2025-09-03",
    location: "Bandung",
    skills: ["UI/UX", "Figma"],
  },
  {
    id: 6,
    name: "Budi santini",
    email: "budi@example.com",
    status: "Pending",
    appliedDate: "2025-09-01",
    location: "Jakarta",
    skills: ["React", "Node.js"],
  },
  {
    id: 7,
    name: "Siti amanah",
    email: "siti@example.com",
    status: "Interview",
    appliedDate: "2025-09-03",
    location: "Bandung",
    skills: ["UI/UX", "Figma"],
  },
];
